# Permalinks
permalink:        pretty

# Setup
url:              http://xuewenchen.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          http://xuewenchen.github.io
# baseurl:           /

title:            catAncle

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
    我的小窝。
# The tags listed as entries in the sidebar
# sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            http://xuewenchen.github.io/public/img/Amy.png
color:            '#A85641'

author:
  name:           'chenxuewen'
  twitter:        ''
  github:         'xuewenchen'
  photo:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, 大家好，我是陈学文，一只喜欢晒太阳的猫~

